### PR TITLE
Converted into a module

### PR DESCRIPTION
**Pull request by scooper4711**
If you zip up the directory and put the URL into the download attribute, then people can download this as a module

### CODE REVIEW

**Comment by Daxiongmao87** [comment]
Hey, thank you.  I've yet to publish any modules, so I'm fairly new to the process.

I think this is a good way to go with this, and would love to make this happen, but I do have a question.  Could we make it so that the images and font are packaged and accessed remotely by the style sheet so that it doesn't have to rely on remote sources? I'm sure some people would like that.

**Comment by scooper4711** [comment]
Good catch - I'll update the css.

As to the name - it's 100% up to you. I can change the name, but even after you pull in my changes, you can make any changes you want. I just wanted to show how this can be made into a module.

**Comment by Daxiongmao87** [comment]
Thank you, once you make those updates I'll, also update the README.md to reflect the changes.

**Comment by scooper4711** [comment]
Done

**Pull request merged**
